### ISSUE TITLE
function specific to PowerModels in InfrastructureModels

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/InfrastructureModels.jl#29]
Why is the function ``function summary(io::IO, data::Dict{String,Any}; float_precision::Int = 3)`` that is doing something specific to PowerModels data in InfrastructureModels?

**Comment by ccoffrin** [comment]
We should generalize the function so that each package can define its own special keywords.  `replicate` provides an example of how to do this.

we might also change the semantics of `float_precision` to be more like significant figures, to work better with a wide range of data scales.
