### ISSUE TITLE
support for user defined index in custom components

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/InfrastructureModels.jl#48]
The matlab parser assumes that the unique id of custom component tables is the row number. It would be nice to allow a column name called index that is then used appropriately, ie

%column_names%  index ...

Currently, this will throw an error message

**Comment by ccoffrin** [comment]
@rb004f, can you test this works for you?  Do you want a new version tagged right away?

**Comment by rb004f** [comment]
I will test. I have hack to get around the issue, so it is not a blocking issue.
